version: '{build}'
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python35"

install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

build: False

test_script:
  - "%PYTHON%/Scripts/py.test"